log = /home/users/hieule/job_logs/log/GNN_$(Cluster)_$(Process).log
output = /home/users/hieule/job_logs/output/GNN_$(Cluster)_$(Process).out
error = /home/users/hieule/job_logs/error/GNN_$(Cluster)_$(Process).error

executable = /home/users/hieule/code/GNN/gnn_icecube/htcondor_multi_main.sh
arguments = $(Step)
request_GPUs = 1
request_memory = 15GB

Universe  = vanilla
+NATIVE_OS = true
requirements = (OpSysMajorVer =?= 7)
notification = Error
notify_user = lehieu1@msu.edu

queue 3

